import { Experience } from '@/types/experience'

export const experiences: Experience[] = [

  // ─── ACUÁTICAS ───────────────────────────────────────────────────────────────

  {
    id: 'submarine-safari',
    slug: 'submarino-safari-tenerife',
    title: 'Submarino Safari',
    subtitle: 'Sin traje, sin buceo, sin miedo. El océano a 30 metros de profundidad.',
    description:
      'Desciende 30 metros bajo el Atlántico en un submarino real con ventanillas de 60 cm. Rayas, morenas, bancos de peces tropicales y un naufragio aguardan bajo la superficie. Guía en 15 idiomas incluido. Apto para toda la familia.',
    price: 37,
    priceLabel: 'Desde €37',
    pricingTiers: [
      { label: 'Adulto (Sur)', price: 61 },
      { label: 'Niño 2-14 (Sur)', price: 37 },
      { label: 'Adulto (Norte)', price: 74 },
    ],
    rating: 4.95,
    reviewCount: 20,
    duration: '1 hora',
    maxGroupSize: 12,
    image: 'https://images.unsplash.com/photo-1682687220063-4742bd7fd538?w=800&q=80',
    imageAlt: 'Submarino Safari en las profundidades del Atlántico, Tenerife',
    badge: 'MEJOR VALORADO ★★★★★',
    highlights: [
      'Sin licencia de buceo — apto para todos',
      'Apto para niños desde 2 años',
      'Guía marino en 15 idiomas a bordo',
    ],
    includes: ['Guía experto', 'Certificado de buceo', 'Traslado en bus gratuito'],
    requirements: ['Edad mínima: 2 años'],
    category: 'acuatica',
    available: true,
    urgencyText: 'Precio especial solo esta semana',
  },
  {
    id: 'whale-catamaran-kailani',
    slug: 'avistamiento-ballenas-kailani',
    title: 'Kailani Whale Watching',
    subtitle: 'Máximo 10 personas. Ballenas, delfines y snorkel en bahía privada.',
    description:
      'El avistamiento de cetáceos más exclusivo de Tenerife: solo 10 plazas por salida a bordo de un velero privado. Parada de snorkel en una bahía tranquila, aperitivos y la promesa de que los gigantes del Atlántico aparecerán.',
    price: 50,
    priceLabel: 'Desde €50',
    pricingTiers: [
      { label: 'Adulto', price: 65 },
      { label: 'Niño 1-8', price: 50 },
      { label: 'Bebé <1 año', price: 0 },
    ],
    rating: 5.0,
    reviewCount: 23,
    duration: '3 horas',
    maxGroupSize: 10,
    image: 'https://images.unsplash.com/photo-1568430462989-44163eb1752f?w=800&q=80',
    imageAlt: 'Avistamiento de ballenas en velero privado, Tenerife',
    badge: 'GRUPO PEQUEÑO',
    highlights: [
      'Solo 10 plazas — experiencia íntima',
      'Snorkel en bahía privada incluido',
      'Aperitivos y bebidas a bordo',
    ],
    includes: ['Equipo de snorkel', 'Aperitivos y bebidas', 'Patrón profesional'],
    category: 'acuatica',
    available: true,
    urgencyText: 'Solo 10 plazas — se agotan rápido',
  },
  {
    id: 'jet-ski-puerto-colon',
    slug: 'jet-ski-puerto-colon',
    title: 'Jet Ski Puerto Colón',
    subtitle: 'Velocidad, adrenalina y el Atlántico bajo tus pies.',
    description:
      'Conduce tu propio Jet Ski por las aguas cristalinas del sur de Tenerife. Rutas guiadas a lo largo de la costa, con vistas a Los Gigantes y paradas en calas escondidas. Sin experiencia previa necesaria.',
    price: 120,
    priceLabel: 'Desde €120',
    pricingTiers: [
      { label: 'Puerto Colón', price: 120 },
      { label: 'Los Gigantes (1h)', price: 130 },
    ],
    rating: 4.86,
    reviewCount: 14,
    duration: '1 hora',
    maxGroupSize: 6,
    image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
    imageAlt: 'Jet Ski en la costa sur de Tenerife',
    highlights: [
      'Guía certificado incluido',
      'Chalecos salvavidas y equipo de seguridad',
      'Sin experiencia previa necesaria',
    ],
    includes: ['Equipo de seguridad completo', 'Guía acuático', 'Briefing de seguridad'],
    category: 'acuatica',
    available: true,
  },
  {
    id: 'kayak-snorkel',
    slug: 'kayak-snorkel-tortugas',
    title: 'Kayak + Snorkel (Delfines y Tortugas)',
    subtitle: 'Rema hasta la Cueva de la Palma y nada junto a tortugas marinas.',
    description:
      'Desde Los Cristianos, remerás hasta la cueva de Palm Mar donde tortugas y delfines son habituales. 2 horas en kayak más 30 minutos de snorkel en aguas cristalinas. Guía instructor certificado incluido.',
    price: 22.5,
    priceLabel: 'Desde €22.50',
    pricingTiers: [
      { label: 'Adulto', price: 45 },
      { label: 'Niño 6-10', price: 22.5 },
    ],
    rating: 4.91,
    reviewCount: 11,
    duration: '2.5 horas',
    maxGroupSize: 10,
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
    imageAlt: 'Kayak y snorkel con tortugas en Tenerife',
    highlights: [
      'Tortugas marinas y delfines habituales',
      'Snorkel en cueva privada incluido',
      'Equipo completo proporcionado',
    ],
    includes: ['Kayak y remo', 'Chaleco salvavidas', 'Gafas y tubo de snorkel', 'Instructor certificado'],
    requirements: ['Edad mínima: 6 años', 'Peso máximo: 120 kg'],
    category: 'acuatica',
    available: true,
  },
  {
    id: 'scuba-diving',
    slug: 'buceo-scuba-tenerife',
    title: 'Buceo PADI Tenerife',
    subtitle: 'Primera inmersión o certificación PADI en el Atlántico más cálido de Europa.',
    description:
      '6 zonas de buceo de 6 a 38 metros de profundidad con fauna atlántica única. Desde primera inmersión para principiantes hasta cursos PADI Open Water completos. Instructores internacionales, material incluido.',
    price: 50,
    priceLabel: 'Desde €50',
    pricingTiers: [
      { label: 'Primera inmersión (principiantes)', price: 70 },
      { label: 'Buceador certificado (1 inmersión)', price: 50 },
      { label: 'PADI Discover Scuba', price: 115 },
      { label: 'PADI Open Water (18m)', price: 400 },
    ],
    rating: 5.0,
    reviewCount: 12,
    duration: '2-4 horas',
    maxGroupSize: 8,
    image: 'https://images.unsplash.com/photo-1544551763-92ab472cad5d?w=800&q=80',
    imageAlt: 'Buceo PADI en Tenerife con fauna atlántica',
    highlights: [
      '6 zonas de buceo de 6 a 38m',
      'Instructores PADI certificados',
      'Traslado gratuito desde el sur',
    ],
    includes: ['Equipo completo', 'Instructor certificado', 'Traslado gratuito (sur Tenerife)'],
    requirements: ['Edad mínima: 10 años', 'Certificado médico recomendado'],
    category: 'acuatica',
    available: true,
  },
  {
    id: 'boat-party-utopia',
    slug: 'fiesta-barco-utopia',
    title: 'Utopia Boat Party',
    subtitle: 'DJ, barra libre y el Atlántico como pista de baile. Solo mayores de 18.',
    description:
      'Los sábados, 150 personas, DJs en directo, hip-hop, reggaeton, house y EDM a bordo de un catamarán. Parada para bañarse en el océano. 4 bebidas incluidas en el ticket básico, barra libre en VIP.',
    price: 70,
    priceLabel: 'Desde €70',
    pricingTiers: [
      { label: 'Básico (4 consumiciones)', price: 70 },
      { label: 'Standard (barra libre)', price: 90 },
      { label: 'Premium (barra libre + zona)', price: 110 },
      { label: 'VIP', price: 130 },
    ],
    rating: 5.0,
    reviewCount: 5,
    duration: '3 horas',
    maxGroupSize: 150,
    image: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80',
    imageAlt: 'Fiesta en barco Utopia Boat Party, Tenerife',
    badge: 'SOLO SÁBADOS',
    highlights: [
      'DJs en directo — 3 géneros musicales',
      'Parada de baño en el océano',
      'Salida previa en Black Pearl Bar',
    ],
    includes: ['DJ y MC profesional', 'Bebidas según ticket', 'Seguridad y tripulación'],
    requirements: ['Edad mínima: 18 años', 'Solo sábados a las 15:30 desde Puerto Colón'],
    category: 'acuatica',
    available: true,
  },

  // ─── AÉREAS ─────────────────────────────────────────────────────────────────

  {
    id: 'paragliding-tandem',
    slug: 'parapente-biplaza-tenerife',
    title: 'Parapente Biplaza',
    subtitle: 'Desde 800m hasta 2.200m de altura. El volcán y el océano a tus pies.',
    description:
      'El vuelo biplaza más espectacular de Canarias: suspendido entre el Teide y el Atlántico con un piloto certificado FAI. 4 opciones de vuelo según la altura y duración que elijas. Fotos y vídeo disponibles.',
    price: 110,
    priceLabel: 'Desde €110',
    pricingTiers: [
      { label: 'Vuelo #1 — 800m (10-12 min)', price: 110 },
      { label: 'Vuelo #2 — 1.000m (15-25 min)', price: 130 },
      { label: 'Vuelo #2 Largo (20-30 min)', price: 150 },
      { label: 'Vuelo #3 — 2.200m (35+ min)', price: 200 },
    ],
    rating: 4.85,
    reviewCount: 40,
    duration: '10 min – 35+ min',
    maxGroupSize: 1,
    image: 'https://images.unsplash.com/photo-1503220317375-aaad61436b1b?w=800&q=80',
    imageAlt: 'Parapente biplaza sobre el océano Atlántico en Tenerife',
    badge: 'MÁS VALORADO',
    highlights: [
      'Piloto certificado FAI incluido',
      'Sin experiencia previa necesaria',
      'Traslado hotel incluido',
    ],
    includes: ['Piloto certificado', 'Todo el equipo de seguridad', 'Traslado desde hotel'],
    requirements: ['Edad mínima: 8 años', 'Peso máximo: 100 kg'],
    category: 'aerea',
    available: true,
    urgencyText: 'Solo 2 plazas disponibles esta semana',
  },
  {
    id: 'helicopter-tours',
    slug: 'tours-helicoptero-tenerife',
    title: 'Tours en Helicóptero',
    subtitle: 'De 7 minutos sobre la costa a 45 minutos sobrevolando el Teide.',
    description:
      'La experiencia aérea definitiva: desde un vuelo de 7-8 minutos sobre las playas del sur hasta el gran tour del Teide de 40-45 minutos cubriendo 120 km de paisajes volcánicos, acantilados y océano. Comentario en directo incluido.',
    price: 110,
    priceLabel: 'Desde €110',
    pricingTiers: [
      { label: 'Sur de Tenerife (7-8 min)', price: 110 },
      { label: 'Playas y Barrancos', price: 159 },
      { label: 'Acantilados Los Gigantes', price: 295 },
      { label: 'Low Island Tour', price: 430 },
      { label: 'Tour El Teide (40-45 min)', price: 545 },
    ],
    rating: 5.0,
    reviewCount: 18,
    duration: '7 – 45 minutos',
    maxGroupSize: 4,
    image: 'https://images.unsplash.com/photo-1474302770737-173ee21bab63?w=800&q=80',
    imageAlt: 'Tour en helicóptero sobre el Teide y la costa de Tenerife',
    badge: 'EXPERIENCIA PREMIUM',
    highlights: [
      'Vistas exclusivas desde el aire',
      'Comentario en directo a bordo',
      'Seguro de actividades incluido',
    ],
    includes: ['Auriculares y comentario', 'Seguro de vuelo', 'Ventanas panorámicas'],
    requirements: ['Peso máximo: 120 kg por persona'],
    category: 'aerea',
    available: true,
  },

  // ─── TIERRA ────────────────────────────────────────────────────────────────

  {
    id: 'quad-teide',
    slug: 'quad-biking-teide',
    title: 'Quad por el Teide',
    subtitle: 'El Parque Nacional más visitado de España. En quad, no en autobús.',
    description:
      'Rutas exclusivas por el Parque Nacional del Teide en quad automático. Desde el tour de 1,5h hasta la ruta completa de 3h con champán al atardecer. Paisajes de otro planeta, acceso a zonas cerradas al tráfico convencional.',
    price: 99,
    priceLabel: 'Desde €99',
    pricingTiers: [
      { label: 'Sunset Fast Ride 1.5h (individual)', price: 99 },
      { label: 'Off-Road South 1.5h (individual)', price: 110 },
      { label: 'Teide Day Tour 3h (individual)', price: 120 },
      { label: 'Teide Sunset 3h (individual)', price: 130 },
      { label: 'Teide Day Tour 3h (doble)', price: 140 },
      { label: 'Puerto de la Cruz 2h (individual)', price: 120 },
    ],
    rating: 4.96,
    reviewCount: 25,
    duration: '1.5 – 3 horas',
    maxGroupSize: 8,
    image: 'https://images.unsplash.com/photo-1558981359-219d6364c9c8?w=800&q=80',
    imageAlt: 'Excursión en quad por el Parque Nacional del Teide, Tenerife',
    badge: 'PLAZAS LIMITADAS',
    highlights: [
      'Acceso a zonas exclusivas del Parque Nacional',
      'Quads automáticos — sin carnet de moto',
      'Champán incluido en tours al atardecer',
    ],
    includes: ['Guía profesional', 'Equipo de seguridad', 'Agua y snacks (ruta norte)'],
    requirements: ['Carnet B vigente', 'Edad mínima: 18 años (7 con consentimiento)', 'Altura mínima: 1,30m'],
    category: 'tierra',
    available: true,
    urgencyText: 'Máximo 8 personas por salida',
  },
  {
    id: 'buggy-safari',
    slug: 'buggy-safari-teide',
    title: 'Buggy Safari Teide',
    subtitle: 'Hasta 6 pasajeros por buggy. 130 km de volcanes, costa y montaña.',
    description:
      'El tour off-road más completo de Tenerife: buggy de hasta 6 plazas por rutas imposibles para vehículos convencionales. 5 rutas diferentes desde 2 hasta 4 horas. Recogida gratuita desde Los Cristianos hasta La Caleta.',
    price: 150,
    priceLabel: 'Desde €150',
    pricingTiers: [
      { label: 'Costa 2h (individual)', price: 150 },
      { label: 'Costa 3h (individual)', price: 190 },
      { label: 'Teide 3h (individual)', price: 190 },
      { label: 'Teide 4h (individual)', price: 210 },
      { label: 'Teide 4h (6 plazas)', price: 450 },
    ],
    rating: 4.84,
    reviewCount: 50,
    duration: '2 – 4 horas',
    maxGroupSize: 6,
    image: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80',
    imageAlt: 'Buggy Safari por los paisajes volcánicos del Teide, Tenerife',
    highlights: [
      'Hasta 6 pasajeros por buggy',
      'Recogida gratuita sur de Tenerife',
      'Bebida gratuita incluida',
    ],
    includes: ['Guías profesionales', 'Equipo de seguridad', 'Recogida en hotel', 'Bebida de bienvenida'],
    requirements: ['Carnet B (2+ años)', 'Edad mínima conductores: 18 años', 'Altura mínima: 1,20m'],
    category: 'tierra',
    available: true,
  },
  {
    id: 'mustang-tour',
    slug: 'tour-mustang-descapotable',
    title: 'Conduce un Ford Mustang Descapotable',
    subtitle: 'El Teide, Pico Viejo y el atardecer más impresionante del mundo. En Mustang.',
    description:
      'Convoy de Mustang Convertibles automáticos por el Parque Nacional del Teide hasta los 2.100m de Pico Viejo. Aperitivo de bienvenida, snack final y guía experto. La experiencia más cinematográfica de la isla.',
    price: 250,
    priceLabel: 'Desde €250',
    pricingTiers: [
      { label: '1-2 pasajeros', price: 250 },
      { label: '3-4 pasajeros', price: 350 },
    ],
    rating: 5.0,
    reviewCount: 2,
    duration: '3 – 3.5 horas',
    maxGroupSize: 4,
    image: 'https://images.unsplash.com/photo-1567818735868-e71b99932e29?w=800&q=80',
    imageAlt: 'Ford Mustang descapotable en el Parque Nacional del Teide, Tenerife',
    badge: 'EXPERIENCIA ÚNICA',
    highlights: [
      'Mustang Convertible automático',
      'Recogida gratuita desde el sur',
      'Aperitivo y snack incluidos',
    ],
    includes: ['Mustang descapotable automático', 'Guía experto', 'Aperitivo + snack final', 'Traslado sur'],
    requirements: ['Carnet de conducir válido (1+ año)', 'Edad mínima: 21 años', 'Calzado cerrado obligatorio'],
    category: 'tierra',
    available: true,
  },

  // ─── TOURS GUIADOS ──────────────────────────────────────────────────────────

  {
    id: 'teide-visit',
    slug: 'tour-parque-nacional-teide',
    title: 'Tour Parque Nacional del Teide',
    subtitle: 'El volcán más alto de España. Patrimonio de la UNESCO. 3.718 metros.',
    description:
      'El Teide en bus con guía experto en inglés: bosque de pinos canarios, Roques de García, Vilaflor y opción de teleférico hasta los 3.500m. 8 horas que explican por qué este parque es el más visitado de toda España.',
    price: 30,
    priceLabel: 'Desde €30',
    pricingTiers: [
      { label: 'Adulto (solo tour)', price: 48 },
      { label: 'Niño 3-13 (solo tour)', price: 30 },
      { label: 'Adulto (tour + teleférico)', price: 89 },
      { label: 'Niño 3-13 (tour + teleférico)', price: 50.5 },
    ],
    rating: 4.75,
    reviewCount: 4,
    duration: '8 horas',
    maxGroupSize: 40,
    image: 'https://images.unsplash.com/photo-1580137189272-c9379f8864fd?w=800&q=80',
    imageAlt: 'Visita guiada al Parque Nacional del Teide, UNESCO, Tenerife',
    highlights: [
      'Guía en inglés incluido',
      'Bus climatizado todo el recorrido',
      'Teleférico opcional hasta 3.500m',
    ],
    includes: ['Guía bilingüe', 'Bus climatizado', 'Teleférico (opción premium)'],
    category: 'tour',
    available: true,
  },
  {
    id: 'teide-night',
    slug: 'teide-noche-estrellas',
    title: 'Teide por la Noche (Puesta de Sol + Estrellas)',
    subtitle: 'El Destino Starlight más famoso del mundo. El cielo más claro de Europa.',
    description:
      'Atardecer desde los 3.718m y astronomía nocturna en el Destino Starlight de la UNESCO. Guía láser para identificar constelaciones, cena en el restaurante del parque y regreso nocturno con el cielo más estrellado que hayas visto nunca.',
    price: 55,
    priceLabel: 'Desde €55',
    pricingTiers: [
      { label: 'Adulto', price: 89 },
      { label: 'Niño hasta 11 años', price: 55 },
    ],
    rating: 4.89,
    reviewCount: 9,
    duration: '9 horas',
    maxGroupSize: 40,
    image: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800&q=80',
    imageAlt: 'Teide por la noche con astronomía y puesta de sol, Tenerife',
    badge: 'DESTINO STARLIGHT UNESCO',
    highlights: [
      'Puesta de sol en la cima del Teide',
      'Astronomía con puntero láser',
      'Cena en restaurante del parque',
    ],
    includes: ['Traslado desde hotel', 'Guía profesional', 'Cena', 'Explicación astronómica con láser'],
    category: 'tour',
    available: true,
    urgencyText: 'Plazas limitadas — tour nocturno exclusivo',
  },
  {
    id: 'teide-masca-tour',
    slug: 'tour-teide-masca-garachico',
    title: 'Teide, Masca, Garachico e Icod',
    subtitle: 'Jornada completa: 4 iconos de Tenerife en un solo día.',
    description:
      'El tour panorámico más completo de la isla: Vilaflor a 2.500m, el Teide, el Drago Milenario de Icod, la historia volcánica de Garachico y los barrancos piratas de Masca. 9 horas con guía apasionado.',
    price: 37,
    priceLabel: 'Desde €37',
    pricingTiers: [
      { label: 'Adulto', price: 55 },
      { label: 'Niño 2-11', price: 37 },
    ],
    rating: 5.0,
    reviewCount: 4,
    duration: '9 horas',
    maxGroupSize: 45,
    image: 'https://images.unsplash.com/photo-1558981359-219d6364c9c8?w=800&q=80',
    imageAlt: 'Tour completo Teide, Masca, Garachico e Icod en Tenerife',
    highlights: [
      '4 destinos icónicos en un día',
      'Guía experto y apasionado',
      'Salida diaria a las 8:00',
    ],
    includes: ['Guía en inglés', 'Bus climatizado'],
    category: 'tour',
    available: true,
  },
  {
    id: 'la-gomera',
    slug: 'excursion-la-gomera',
    title: 'Excursión a La Gomera',
    subtitle: 'La isla del silbido. Bosque laurisilva UNESCO y el legado de Colón.',
    description:
      'Ferry a La Gomera, Valle de Hermigua, el pueblo de Agulo, el Parque Nacional de Garajonay (bosque de laurisilva UNESCO) y los lugares históricos de Cristóbal Colón. Demostración del Silbo Gomero incluida. Almuerzo típico.',
    price: 75,
    priceLabel: 'Desde €75',
    pricingTiers: [
      { label: 'Adulto (desde Sur)', price: 105 },
      { label: 'Niño 2-11 (desde Sur)', price: 75 },
      { label: 'Adulto (desde Norte)', price: 111 },
    ],
    rating: 5.0,
    reviewCount: 5,
    duration: '10 horas',
    maxGroupSize: 50,
    image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=80',
    imageAlt: 'Excursión a La Gomera, laurisilva UNESCO y valle de Hermigua',
    highlights: [
      'Ferry + guía + almuerzo incluido',
      'Parque Nacional Garajonay (UNESCO)',
      'Demo del Silbo Gomero',
    ],
    includes: ['Traslado desde hotel', 'Billetes de ferry', 'Guía bilingüe', 'Bus en La Gomera', 'Almuerzo típico'],
    category: 'tour',
    available: true,
  },

  // ─── PARQUES ────────────────────────────────────────────────────────────────

  {
    id: 'siam-park',
    slug: 'siam-park-tenerife',
    title: 'Siam Park — Mejor Parque Acuático del Mundo',
    subtitle: 'TripAdvisor lo ha elegido el mejor parque acuático del planeta 8 veces.',
    description:
      'El "Tower of Power" vertical a través de un tanque de tiburones, la ola artificial más alta del mundo y el río lento más espectacular de Europa. Desde el ticket básico hasta cabañas VIP privadas con jacuzzi.',
    price: 32,
    priceLabel: 'Desde €32',
    pricingTiers: [
      { label: 'Adulto (día estándar)', price: 44 },
      { label: 'Niño 3-11 (día estándar)', price: 32 },
      { label: 'Todo Incluido adulto', price: 165 },
      { label: 'Siam Night (adulto)', price: 48 },
    ],
    rating: 4.7,
    reviewCount: 10,
    duration: '5-7 horas',
    maxGroupSize: 999,
    image: 'https://images.unsplash.com/photo-1560541959-2b0b0d2ab6a5?w=800&q=80',
    imageAlt: 'Siam Park Tenerife, mejor parque acuático del mundo',
    badge: '#1 MUNDO TRIPADVISOR',
    highlights: [
      'Tower of Power — tanque de tiburones',
      'Olas artificiales más altas del mundo',
      'VIP con cabaña privada disponible',
    ],
    includes: ['Entrada al parque', 'Acceso a todas las atracciones'],
    category: 'parque',
    available: true,
  },
  {
    id: 'loro-parque',
    slug: 'loro-parque-tenerife',
    title: 'Loro Parque — Mejor Zoo de Europa',
    subtitle: '+400 especies: orcas, pingüinos, tigres blancos y el loro más famoso del mundo.',
    description:
      'El zoo más premiado de Europa con 400 especies en hábitats naturales espectaculares. Shows de orcas, delfines, focas y loros. Hábitat antártico con nieve artificial para los pingüinos. Diamond Tour con almuerzo en Brunelli\'s disponible.',
    price: 32,
    priceLabel: 'Desde €32',
    pricingTiers: [
      { label: 'Adulto', price: 44 },
      { label: 'Niño 3-11', price: 32 },
      { label: 'Todo Incluido adulto', price: 132 },
      { label: 'Diamond Tour adulto', price: 127 },
    ],
    rating: 4.69,
    reviewCount: 16,
    duration: '5-7 horas',
    maxGroupSize: 999,
    image: 'https://images.unsplash.com/photo-1589656966895-2f33e7653819?w=800&q=80',
    imageAlt: 'Loro Parque Tenerife, zoo con pingüinos, orcas y tigres blancos',
    highlights: [
      '+400 especies en hábitats naturales',
      'Shows de orcas, delfines y loros',
      'Pingüinos con nieve artificial',
    ],
    includes: ['Entrada al parque', 'Shows incluidos'],
    category: 'parque',
    available: true,
  },

  // ─── GASTRONOMÍA ────────────────────────────────────────────────────────────

  {
    id: 'wine-routes',
    slug: 'rutas-del-vino-tenerife',
    title: 'Rutas del Vino de Tenerife',
    subtitle: 'Malvasía volcánica, bodegas centenarias y el Teide al fondo de tu copa.',
    description:
      'Visita a la Finca Las Margaritas (plantación de bananas), el pueblo de Vilaflor y la Bodega Lagar de Chasna para una cata de vinos con productos locales. Los vinos que nunca salen de Tenerife, en su tierra.',
    price: 69,
    priceLabel: '€69',
    pricingTiers: [
      { label: 'Adulto / Niño 2-17', price: 69 },
    ],
    rating: 0,
    reviewCount: 0,
    duration: '4-5 horas',
    maxGroupSize: 40,
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80',
    imageAlt: 'Cata de vinos volcánicos en bodegas del Teide, Tenerife',
    badge: 'EXPERIENCIA GASTRONÓMICA',
    highlights: [
      'Visita a bodega artesanal centenaria',
      'Degustación de malvasía volcánico',
      'Maridaje con productos locales',
    ],
    includes: ['Bus climatizado', 'Guía profesional', 'Entrada a finca bananera', 'Cata de vinos y tapas locales'],
    requirements: ['Accesible para sillas de ruedas (máx. 2 por bus)'],
    category: 'gastronomia',
    available: true,
  },
  {
    id: 'medieval-show',
    slug: 'espectaculo-medieval-tenerife',
    title: 'Espectáculo Medieval y Cena',
    subtitle: 'Torneos, halconería, fuego y un banquete de 3 platos. Solo martes, jueves y sábados.',
    description:
      'En el Castillo de San Miguel: 2h 45min de torneos medievales a caballo, acrobacias ecuestres, halconería y shows de fuego. Cena de 3 platos (pollo con salsa de champiñones, verduras y tarta de helado) con vino, agua y refresco.',
    price: 23.20,
    priceLabel: 'Desde €23.20',
    pricingTiers: [
      { label: 'Adulto (sin traslado)', price: 49.50 },
      { label: 'Niño hasta 13 (sin traslado)', price: 23.20 },
      { label: 'VIP adulto (sin traslado)', price: 59.50 },
      { label: 'Adulto (con traslado)', price: 64.50 },
    ],
    rating: 5.0,
    reviewCount: 2,
    duration: '2h 45min',
    maxGroupSize: 200,
    image: 'https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=800&q=80',
    imageAlt: 'Espectáculo medieval con torneos y cena en el Castillo de San Miguel, Tenerife',
    highlights: [
      'Torneos, halconería y fuego en vivo',
      'Cena de 3 platos incluida',
      'Personal multilingüe (ES, EN, DE, IT, RU)',
    ],
    includes: ['Espectáculo medieval completo', 'Cena de 3 platos', 'Vino, agua y refresco', 'Traslado opcional'],
    requirements: ['Solo martes, jueves y sábados', 'Apertura puertas: 18:30 — Inicio show: 19:30'],
    category: 'gastronomia',
    available: true,
  },
]

export const categories = [
  { id: 'all', label: 'Todos' },
  { id: 'acuatica', label: 'Acuáticas' },
  { id: 'aerea', label: 'Aéreas' },
  { id: 'tierra', label: 'Tierra' },
  { id: 'tour', label: 'Tours' },
  { id: 'parque', label: 'Parques' },
  { id: 'gastronomia', label: 'Gastronomía' },
] as const
