import { Experience } from '@/types/experience'

export const experiences: Experience[] = [

  // ─── ACUÁTICAS ───────────────────────────────────────────────────────────────
  {
    id: 'jet-ski-puerto-colon',
    slug: 'jet-ski-puerto-colon',
    title: 'Jet Ski Puerto Colón',
    subtitle: 'Velocidad, adrenalina y el Atlántico bajo tus pies.',
    description:
      'Conduce tu propio Jet Ski por las aguas cristalinas del sur de Tenerife. Rutas guiadas a lo largo de la costa, con vistas a Los Gigantes y paradas en calas escondidas. Sin experiencia previa necesaria.',
    price: 50,
    priceLabel: 'Reserva desde €50',
    pricingTiers: [
      { label: '"Adrenalina" Individual — 40 min',   price: 90,  deposit: 50,  perPerson: false },
      { label: '"Adrenalina" Doble — 40 min',        price: 110, deposit: 70,  perPerson: false },
      { label: '"Aventuras" Individual — 1 hora',    price: 130, deposit: 80,  perPerson: false },
      { label: '"Aventuras" Doble — 1 hora',         price: 150, deposit: 100, perPerson: false },
      { label: '"VIP King Cruiser" Individual — 2h', price: 180, deposit: 80,  perPerson: false },
      { label: '"VIP King Cruiser" Doble — 2h',      price: 200, deposit: 100, perPerson: false },
    ],
    rating: 4.86,
    reviewCount: 14,
    duration: '40 min – 2 horas',
    maxGroupSize: 2,
    image: '/images/jet-ski-puerto-colon.jpg',
    imageAlt: 'Jet Ski en la costa sur de Tenerife',
    gallery: [
      '/images/jet-ski-puerto-colon.jpg',
      '/images/jet-ski/jet-ski-2.jpg',
      '/images/jet-ski/jet-ski-3.jpg',
      '/images/jet-ski/jet-ski-4.jpg',
      '/images/jet-ski/jet-ski-5.jpg',
    ],
    highlights: [
      '3 rutas diferentes: 40 min, 1h y 2h',
      'Salidas cada hora de 10:00 a 18:00',
      'Individual o en pareja — sin experiencia previa',
    ],
    includes: ['Equipo de seguridad completo', 'Guía acuático', 'Briefing de seguridad'],
    requirements: ['Llegar 30 minutos antes de la salida', 'Salidas: cada hora de 10:00 a 18:00'],
    category: 'acuatica',
    available: true,
  },
  {
    id: 'scuba-diving',
    slug: 'buceo-scuba-tenerife',
    title: 'Buceo PADI Tenerife',
    subtitle: 'Bautismos, inmersiones y cursos PADI/CMAS en Tenerife Sur.',
    description:
      'Descubre el mundo submarino de Tenerife con opciones para todos los niveles. Desde snorkel y bautismos para principiantes hasta cursos avanzados y excursiones para buceadores certificados. Todas las inmersiones se realizan desde nuestra embarcación.',
    price: 9,
    priceLabel: 'Reserva desde €9',
    pricingTiers: [
      // ── Snorkel ──────────────────────────────────────────────────────
      { label: 'Snorkeling desde barco (~1h)',                   price: 40,  deposit: 10 },
      // ── Débutants ────────────────────────────────────────────────────
      { label: 'Bautismo Clásico — Principiantes',               price: 79,  deposit: 15 },
      { label: 'Bautismo Premium — Principiantes',               price: 139, deposit: 20 },
      { label: 'PADI Discover Scuba Diving',                     price: 149, deposit: 20 },
      { label: 'Stage Découverte — 3 inmersiones',               price: 260, deposit: 30 },
      // ── Buceador Autónomo ─────────────────────────────────────────────
      { label: 'Buceador Autónomo — 1 inmersión',                price: 39,  deposit: 9  },
      { label: 'Buceador Autónomo — 5 inmersiones',              price: 185, deposit: 35 },
      { label: 'Buceador Autónomo — 10 inmersiones',             price: 350, deposit: 50 },
      // ── Cursos PADI ───────────────────────────────────────────────────
      { label: 'Curso PADI Open Water Diver',                    price: 539, deposit: 54 },
      { label: 'Curso PADI Advanced Open Water',                 price: 549, deposit: 55 },
      { label: 'Curso PADI Rescue Diver',                        price: 449, deposit: 45 },
      // ── Cursos CMAS / FFESSM ──────────────────────────────────────────
      { label: 'Curso CMAS/FFESSM Nivel 1',                      price: 449, deposit: 45 },
      { label: 'Curso CMAS/FFESSM Nivel 2',                      price: 489, deposit: 49 },
      { label: 'Curso CMAS/FFESSM Nivel 3',                      price: 799, deposit: 80 },
    ],
    rating: 5.0,
    reviewCount: 12,
    duration: '2-4 horas',
    maxGroupSize: 10,
    image: 'https://images.unsplash.com/photo-1544551763-92ab472cad5d?w=800&q=80',
    imageAlt: 'Buceo PADI y snorkel en Tenerife',
    highlights: [
      'Todas las inmersiones se realizan en barco',
      'Instructores y guías certificados PADI / CMAS / FFESSM',
      'Refresco y snacks disponibles en el centro',
    ],
    includes: ['Equipo incluido (en bautismos y snorkel)', 'Salida en barco', 'Acompañante permitido en barco (sujeto a disponibilidad)'],
    requirements: ['Certificación requerida solo para inmersiones autónomas'],
    category: 'acuatica',
    available: true,
  },
  {
    id: 'speedboat-avistamiento',
    slug: 'speedboat-avistamiento-ballenas-delfines',
    title: 'Speedboat: Ballenas y Delfines',
    subtitle: 'Excursión en barco para el avistamiento de cetáceos en su hábitat natural.',
    description:
      'A bordo de una lancha rápida (speedboat) con capacidad para un máximo de 11 personas, vivirás una experiencia íntima e inolvidable. Navegaremos por la costa en busca de ballenas, tortugas y delfines, con tiempo para nadar y hacer snorkel. Escoge la ruta de 2 o 3 horas, o reserva el barco completo en privado.',
    price: 20,
    priceLabel: 'Reserva desde €20',
    pricingTiers: [
      { label: '2H — Niños (3-12 años)',             price: 35,  deposit: 20, perPerson: true  },
      { label: '2H — Adultos',                        price: 60,  deposit: 30, perPerson: true  },
      { label: '2H — Excursión Privada (barco completo)', price: 300, deposit: 100, perPerson: false },
      { label: '3H — Niños (3-12 años)',             price: 40,  deposit: 20, perPerson: true  },
      { label: '3H — Adultos',                        price: 80,  deposit: 40, perPerson: true  },
      { label: '3H — Excursión Privada (barco completo)', price: 400, deposit: 100, perPerson: false },
    ],
    rating: 4.9,
    reviewCount: 32,
    duration: '2 - 3 horas',
    maxGroupSize: 11,
    image: 'https://images.unsplash.com/photo-1572949645841-094f3a9c4c94?w=800&q=80',
    imageAlt: 'Avistamiento de ballenas y delfines en speedboat Tenerife',
    badge: 'MÁXIMO 11 PERSONAS',
    highlights: [
      'Avistamiento de ballenas, tortugas y delfines',
      'Parada para natación y snorkel',
      'Grupos reducidos (máx. 11 pasajeros) o barco privado',
    ],
    includes: ['Refrigerio y bebida', 'Equipo de snorkel', 'Patrón y guía experto'],
    requirements: ['Llegar 15 minutos antes de la salida', 'Horarios de salida: 10:00 y 13:30'],
    category: 'acuatica',
    available: true,
  },

  // ─── TIERRA ────────────────────────────────────────────────────────────────

  {
    id: 'quad-teide',
    slug: 'quad-biking-teide',
    title: 'Quad por el Teide',
    subtitle: 'Excursión Volcán — 4 horas entre paisajes de otro planeta.',
    description:
      'Descubre el Parque Nacional del Teide a bordo de un quad automático en esta ruta volcánica de 4 horas. Dos salidas diarias: mañana a las 9:30 h y tarde a las 13:15 h. Acceso a zonas cerradas al tráfico convencional, guía experto incluido y paisajes únicos del volcán más alto de España.',
    price: 130,
    priceLabel: 'Desde €130',
    pricingTiers: [
      { label: 'Excursión Volcán — 1 persona (4h)', price: 130, deposit: 50, perPerson: false },
      { label: 'Excursión Volcán — 2 personas (4h)', price: 160, deposit: 50, perPerson: false },
    ],
    rating: 4.96,
    reviewCount: 25,
    duration: '4 horas',
    maxGroupSize: 8,
    image: '/images/quad/quad-1.jpg',
    imageAlt: 'Excursión en quad por el Parque Nacional del Teide, Tenerife',
    gallery: [
      '/images/quad/quad-1.jpg',
      '/images/quad/quad-2.jpg',
      '/images/quad/quad-3.jpg',
    ],
    badge: 'PLAZAS LIMITADAS',
    highlights: [
      'Salidas: 9:30 h (mañana) y 13:15 h (tarde)',
      'Acceso a zonas exclusivas del Parque Nacional',
      'Quads automáticos — sin carnet de moto',
    ],
    includes: ['Guía profesional', 'Equipo de seguridad', 'Agua'],
    requirements: ['Carnet B vigente', 'Edad mínima: 18 años (7 con consentimiento)', 'Altura mínima: 1,30m'],
    category: 'tierra',
    available: true,
    urgencyText: 'Máximo 8 personas por salida',
  },
  {
    id: 'buggy-safari',
    slug: 'buggy-safari-teide',
    title: 'Buggy Safari Teide',
    subtitle: 'Can-Am 700cc · 4 plazas · 6 plazas — Tres excursiones, un paisaje inolvidable.',
    description:
      'Descubre Tenerife a bordo de un buggy Can-Am. Elige entre tres excursiones: Teide 4h (mañana o tarde) con 1h de todoterreno puro; Off-Road 3h (solo mañana) 100% campo a través; o Atardecer 3h al Parque Nacional sin todoterreno. Disponible en buggy de 2 plazas (Can-Am 700cc), 4 plazas (1000cc) o 6 plazas (1000cc).',
    price: 200,
    priceLabel: 'Desde €200',
    pricingTiers: [
      { label: 'Buggy Can-Am 2 plazas — 700cc', price: 200, deposit: 50, perPerson: false },
      { label: 'Buggy 4 plazas — 1000cc',        price: 250, deposit: 50, perPerson: false },
      { label: 'Buggy 6 plazas — 1000cc',        price: 360, deposit: 50, perPerson: false },
    ],
    rating: 4.84,
    reviewCount: 50,
    duration: '3 – 4 horas',
    maxGroupSize: 6,
    image: '/images/buggy/buggy-4.jpg',
    imageAlt: 'Buggy Can-Am en acción por los paisajes volcánicos de Tenerife',
    gallery: [
      '/images/buggy/buggy-4.jpg',
      '/images/buggy/buggy-2.jpg',
      '/images/buggy/buggy-6.jpg',
      '/images/buggy/buggy-3.jpg',
      '/images/buggy/buggy-5.jpg',
      '/images/buggy/buggy-7.jpg',
    ],
    highlights: [
      'Teide 4h · Off-Road 3h · Atardecer 3h — tú eliges',
      'Can-Am 700cc (2 pl.) o 1000cc (4 y 6 pl.)',
      'Recogida gratuita sur de Tenerife',
    ],
    includes: ['Guías profesionales', 'Equipo de seguridad', 'Recogida en hotel', 'Bebida de bienvenida'],
    requirements: ['Carnet B (2+ años)', 'Edad mínima conductores: 18 años', 'Altura mínima: 1,20m'],
    category: 'tierra',
    available: true,
    urgencyText: 'Indica la excursión elegida en "peticiones especiales"',
  }
]

export const categories = [
  { id: 'all', label: 'Todos' },
  { id: 'acuatica', label: 'Acuáticas' },
  { id: 'tierra', label: 'Tierra' },
] as const
