import { Experience } from '@/types/experience'

export const experiences: Experience[] = [
  {
    id: 'paragliding-tandem',
    slug: 'parapente-biplaza-tenerife',
    title: 'Vuela Sobre el Atlántico',
    subtitle: 'La vista que solo el 1% de los turistas llega a ver — desde 700m de altura.',
    description:
      'No lo verás desde un mirador. No lo verás desde un barco. Esta es la única manera de sentir Tenerife como la sienten las gaviotas: suspendido entre el volcán y el océano, con el viento llevándote. Nuestros pilotos certificados internacionales garantizan tu seguridad en cada centímetro del vuelo.',
    price: 110,
    priceLabel: 'Desde €110',
    rating: 4.85,
    reviewCount: 40,
    duration: '2-3 horas',
    maxGroupSize: 1,
    image: 'https://images.unsplash.com/photo-1503220317375-aaad61436b1b?w=800&q=80',
    imageAlt: 'Parapente biplaza sobre el océano Atlántico en Tenerife',
    badge: 'MÁS VALORADO',
    highlights: [
      'Piloto certificado FAI incluido',
      'Fotos y vídeo HD de regalo',
      'Sin experiencia previa necesaria',
    ],
    category: 'aventura',
    available: true,
    urgencyText: 'Solo 2 plazas disponibles esta semana',
  },
  {
    id: 'submarine-safari',
    slug: 'submarino-safari-tenerife',
    title: 'El Mundo a 30 Metros de Profundidad',
    subtitle: 'Sin traje, sin buceo, sin miedo. El océano profundo al alcance de todos.',
    description:
      'La mayoría de los turistas nunca bajan de la superficie. Tú llegarás a 30 metros en un submarino real, rodeado de rayas, morenas y bancos de peces que jamás imaginaste ver. Una experiencia que los niños recordarán a los 40 años.',
    price: 37,
    priceLabel: 'Desde €37',
    rating: 4.95,
    reviewCount: 20,
    duration: '1 hora',
    maxGroupSize: 12,
    image: 'https://images.unsplash.com/photo-1682687220063-4742bd7fd538?w=800&q=80',
    imageAlt: 'Submarino Safari en las profundidades del Atlántico en Tenerife',
    badge: 'MEJOR VALORADO ★★★★★',
    highlights: [
      'Sin licencia de buceo necesaria',
      'Apto para niños desde 4 años',
      'Guía marino bilingüe a bordo',
    ],
    category: 'maritimo',
    available: true,
    urgencyText: 'Precio especial solo esta semana',
  },
  {
    id: 'quad-teide',
    slug: 'quad-biking-teide',
    title: 'Conquista el Volcán en Quad',
    subtitle: 'El Teide, Patrimonio Mundial UNESCO, con el motor entre tus manos.',
    description:
      'Miles de turistas suben al Teide en autobús. Tú subirás en quad, por rutas que los autobuses no pueden tomar, rodeado de un paisaje de otro planeta. La adrenalina del motor, el frío del volcán y las vistas a cuatro islas desde la cima.',
    price: 120,
    priceLabel: 'Desde €120',
    rating: 4.96,
    reviewCount: 25,
    duration: '3-4 horas',
    maxGroupSize: 8,
    image: 'https://images.unsplash.com/photo-1558981359-219d6364c9c8?w=800&q=80',
    imageAlt: 'Excursión en quad por el Parque Nacional del Teide, Tenerife',
    badge: 'PLAZAS LIMITADAS',
    highlights: [
      'Acceso a zonas exclusivas del Parque Nacional',
      'Quads automáticos — sin experiencia requerida',
      'Vistas a Gomera, La Palma y Gran Canaria',
    ],
    category: 'aventura',
    available: true,
    urgencyText: 'Máximo 8 personas por salida',
  },
  {
    id: 'whale-catamaran',
    slug: 'maxicat-cetaceos-avistamiento',
    title: 'Cara a Cara con las Ballenas',
    subtitle: 'El encuentro que los documentales no pueden replicar — en vivo, a metros de ti.',
    description:
      'Las aguas del sur de Tenerife son el hogar permanente de cachalotes y delfines. A bordo de nuestro catamarán ecológico, sin motores ruidosos ni grupos de 100 personas, te acercarás a estos gigantes del océano con la tranquilidad que merecen. Avistamiento garantizado.',
    price: 20,
    priceLabel: 'Desde €20',
    rating: 4.83,
    reviewCount: 12,
    duration: '2 horas',
    maxGroupSize: 20,
    image: 'https://images.unsplash.com/photo-1568430462989-44163eb1752f?w=800&q=80',
    imageAlt: 'Avistamiento de ballenas y delfines en el catamarán MaxiCat, Tenerife',
    highlights: [
      'Catamarán ecológico certificado',
      'Biólogo marino a bordo',
      'Avistamiento garantizado o repetición gratuita',
    ],
    category: 'maritimo',
    available: true,
  },
  {
    id: 'wine-routes',
    slug: 'rutas-del-vino-tenerife',
    title: 'El Secreto Vinícola de las Islas',
    subtitle: 'Los vinos que solo se beben aquí. El Teide al fondo. La tarde perfecta.',
    description:
      'Tenerife produce vinos que nunca salen de la isla. En nuestras rutas de medio día, visitarás bodegas centenarias en las faldas del Teide, conocerás el proceso del malvasía volcánico y degustarás lo que los restaurantes con estrella Michelin sirven en sus mesas.',
    price: 69,
    priceLabel: 'Desde €69',
    rating: 0,
    reviewCount: 0,
    duration: '4 horas',
    maxGroupSize: 6,
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80',
    imageAlt: 'Cata de vinos volcánicos en bodegas del Teide, Tenerife',
    badge: 'GRUPO EXCLUSIVO',
    highlights: [
      'Máximo 6 personas — experiencia íntima',
      '4 bodegas artesanas + 12 vinos',
      'Maridaje con productos locales incluido',
    ],
    category: 'cultura',
    available: true,
  },
  {
    id: 'teide-visit',
    slug: 'visita-parque-nacional-teide',
    title: 'En la Cima del Mundo Antiguo',
    subtitle: 'El tercer volcán más alto del planeta. Patrimonio de la Humanidad. 3.718m.',
    description:
      'El Teide no es solo una montaña: es el alma de Tenerife, un lugar sagrado para los guanches y el punto más alto de España. Nuestro tour incluye el teleférico, zonas exclusivas del cráter y un guía experto que transforma el paisaje en historia viva.',
    price: 30,
    priceLabel: 'Desde €30',
    rating: 4.75,
    reviewCount: 4,
    duration: '5-6 horas',
    maxGroupSize: 10,
    image: 'https://images.unsplash.com/photo-1580137189272-c9379f8864fd?w=800&q=80',
    imageAlt: 'Visita guiada al Parque Nacional del Teide, UNESCO, Tenerife',
    highlights: [
      'Transporte privado desde tu hotel',
      'Teleférico y zonas exclusivas incluidos',
      'Guía historiador certificado',
    ],
    category: 'naturaleza',
    available: true,
  },
]
